export default [
  {
    users: [
      {
        id: 1,
        email: "user1@example.com",
        password: "password1",
      },
      {
        id: 2,
        email: "user2@example.com",
        password: "password2",
      },
      {
        id: 3,
        email: "user3@example.com",
        password: "password3",
      },
      {
        id: 4,
        email: "user4@example.com",
        password: "password4",
      },
      {
        id: 5,
        email: "user5@example.com",
        password: "password5",
      },
      {
        id: 6,
        email: "user6@example.com",
        password: "password6",
      },
      {
        id: 7,
        email: "user7@example.com",
        password: "password7",
      },
      {
        id: 8,
        email: "user8@example.com",
        password: "password8",
      },
      {
        id: 9,
        email: "user9@example.com",
        password: "password9",
      },
      {
        id: 10,
        email: "user10@example.com",
        password: "password10",
      },
    ],
    events: [
      {
        id: 1,
        title: "Exhibition 1",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-10-08",
        availableSeats: 40,
        price: 100,
      },
      {
        id: 2,
        title: "Conference 2",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-07-19",
        availableSeats: 77,
        price: 180,
      },
      {
        id: 3,
        title: "Game 3",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-12-14",
        availableSeats: 61,
        price: 163,
      },
      {
        id: 4,
        title: "Festival 4",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-10-27",
        availableSeats: 30,
        price: 87,
      },
      {
        id: 5,
        title: "Concert 5",
        description: "An amazing event.",
        category: "Music",
        date: "2024-12-25",
        availableSeats: 100,
        price: 152,
      },
      {
        id: 6,
        title: "Exhibition 6",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-08-10",
        availableSeats: 105,
        price: 244,
      },
      {
        id: 7,
        title: "Conference 7",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-09-27",
        availableSeats: 84,
        price: 154,
      },
      {
        id: 8,
        title: "Game 8",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-08-15",
        availableSeats: 57,
        price: 234,
      },
      {
        id: 9,
        title: "Festival 9",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-05-26",
        availableSeats: 32,
        price: 71,
      },
      {
        id: 10,
        title: "Concert 10",
        description: "An amazing event.",
        category: "Music",
        date: "2024-12-07",
        availableSeats: 84,
        price: 83,
      },
      {
        id: 11,
        title: "Exhibition 11",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-07-21",
        availableSeats: 45,
        price: 210,
      },
      {
        id: 12,
        title: "Conference 12",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-07-03",
        availableSeats: 68,
        price: 98,
      },
      {
        id: 13,
        title: "Game 13",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-08-20",
        availableSeats: 66,
        price: 95,
      },
      {
        id: 14,
        title: "Festival 14",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-07-13",
        availableSeats: 23,
        price: 183,
      },
      {
        id: 15,
        title: "Concert 15",
        description: "An amazing event.",
        category: "Music",
        date: "2024-05-01",
        availableSeats: 90,
        price: 156,
      },
      {
        id: 16,
        title: "Exhibition 16",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-11-15",
        availableSeats: 106,
        price: 64,
      },
      {
        id: 17,
        title: "Conference 17",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-12-04",
        availableSeats: 83,
        price: 230,
      },
      {
        id: 18,
        title: "Game 18",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-08-27",
        availableSeats: 42,
        price: 63,
      },
      {
        id: 19,
        title: "Festival 19",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-10-12",
        availableSeats: 46,
        price: 154,
      },
      {
        id: 20,
        title: "Concert 20",
        description: "An amazing event.",
        category: "Music",
        date: "2024-03-23",
        availableSeats: 48,
        price: 154,
      },
      {
        id: 21,
        title: "Exhibition 21",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-04-16",
        availableSeats: 101,
        price: 191,
      },
      {
        id: 22,
        title: "Conference 22",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-09-05",
        availableSeats: 104,
        price: 149,
      },
      {
        id: 23,
        title: "Game 23",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-08-23",
        availableSeats: 97,
        price: 212,
      },
      {
        id: 24,
        title: "Festival 24",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-02-03",
        availableSeats: 80,
        price: 198,
      },
      {
        id: 25,
        title: "Concert 25",
        description: "An amazing event.",
        category: "Music",
        date: "2024-02-07",
        availableSeats: 71,
        price: 221,
      },
      {
        id: 26,
        title: "Exhibition 26",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-01-26",
        availableSeats: 34,
        price: 85,
      },
      {
        id: 27,
        title: "Conference 27",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-07-14",
        availableSeats: 54,
        price: 104,
      },
      {
        id: 28,
        title: "Game 28",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-11-17",
        availableSeats: 33,
        price: 198,
      },
      {
        id: 29,
        title: "Festival 29",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-02-06",
        availableSeats: 109,
        price: 197,
      },
      {
        id: 30,
        title: "Concert 30",
        description: "An amazing event.",
        category: "Music",
        date: "2024-08-24",
        availableSeats: 41,
        price: 126,
      },
      {
        id: 31,
        title: "Exhibition 31",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-10-25",
        availableSeats: 86,
        price: 174,
      },
      {
        id: 32,
        title: "Conference 32",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-06-05",
        availableSeats: 22,
        price: 243,
      },
      {
        id: 33,
        title: "Game 33",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-01-23",
        availableSeats: 104,
        price: 70,
      },
      {
        id: 34,
        title: "Festival 34",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-06-26",
        availableSeats: 67,
        price: 178,
      },
      {
        id: 35,
        title: "Concert 35",
        description: "An amazing event.",
        category: "Music",
        date: "2024-12-06",
        availableSeats: 28,
        price: 162,
      },
      {
        id: 36,
        title: "Exhibition 36",
        description: "A fantastic opportunity.",
        category: "Art",
        date: "2024-07-07",
        availableSeats: 91,
        price: 199,
      },
      {
        id: 37,
        title: "Conference 37",
        description: "Join us for a unique experience.",
        category: "Technology",
        date: "2024-04-12",
        availableSeats: 42,
        price: 241,
      },
      {
        id: 38,
        title: "Game 38",
        description: "A must-see event.",
        category: "Sports",
        date: "2024-10-10",
        availableSeats: 117,
        price: 200,
      },
      {
        id: 39,
        title: "Festival 39",
        description: "An unforgettable gathering.",
        category: "Food",
        date: "2024-03-15",
        availableSeats: 20,
        price: 58,
      },
      {
        id: 40,
        title: "Concert 40",
        description: "An amazing event.",
        category: "Music",
        date: "2024-09-06",
        availableSeats: 65,
        price: 129,
      },
    ],
  },
];
